{
  imports = [
    ./argumentative.nix
    ./diffchar.nix
    ./exchange.nix
    ./fugitive.nix
    ./fzf.nix
    ./git.nix
    ./hop.nix
    ./mini.nix
    ./mundo.nix
    ./neogit.nix
    ./neorg
    ./nerdcommenter.nix
    ./oil.nix
    ./peekaboo.nix
    ./silicon.nix
    ./tabular.nix
    ./telescope.nix
    ./tpope.nix
    ./update-nix-fetchgit.nix
    ./ultisnips
    ./vista.nix
  ];
}
