{
  imports = [
    ./options.nix

    ./atuin.nix
    ./azure.nix
    ./bat.nix
    ./disable-news.nix
    ./git
    ./gnupg.nix
    ./go.nix
    ./gui
    ./latex.nix
    ./libreoffice.nix
    ./lsd.nix
    ./lsp.nix
    ./mac
    ./readline.nix
    ./revcli.nix
    ./packages-core.nix
    ./packages-extended.nix
    ./terraform.nix
    ./tmux.nix
    ./work.nix
    ./wrepson.nix
    ./xsession
    ./zellij.nix
    ./zsh.nix
  ];
}
